name: CI/CD for Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H  ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Deploying to VPS..."
            cd /projects
            git clone
            cd audio-library
            git pull
            npm install
            npm run build
            export PATH=\$PATH:/root/.nvm/versions/node/v20.18.0/bin
            if pm2 describe audio-library > /dev/null; then
              pm2 restart audio-library --update-env;
            else
              pm2 start npm --name "audio-library" -- start --prefix /projects/audio-library;
            fi
            pm2 save
