name: CI/CD for Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H  ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          APP_NAME: 'audio-library'
        run: |
          echo "Deploying to VPS..."
          sshpass -p "$VPS_PASSWORD" ssh $VPS_USER@$VPS_IP "
            cd /projects &&
            git pull origin main &&
            npm install &&
            npm run build &&
            export PATH=\$PATH:/root/.nvm/versions/node/v20.18.0/bin &&
            if pm2 describe $APP_NAME > /dev/null; then
              pm2 restart $APP_NAME --update-env;
            else
              pm2 start npm --name \"$APP_NAME\" -- start --prefix /projects/$APP_NAME;
            fi
            pm2 save
          "
